import random
from termcolor import colored

fun_facts = [
    ("Birthplace of chess", "The game was originally known as 'chaturanga.'"),
    ("Largest democracy",
     "India is the world's largest democracy with over 1.3 billion citizens."),
    ("Variety of languages", "India is home to over 21 officially recognized languages."),
    ("Spice capital of the world",
     "India is known as the spice capital of the world, producing and exporting a variety of spices."),
    ("Bollywood", "India is home to the world's largest film industry, producing over 1,000 films per year."),
    ("Yoga origin", "Yoga originated in ancient India and has since gained global popularity."),
    ("Golden Triangle", "India's Golden Triangle, made up of Delhi, Agra, and Jaipur, is a popular tourist destination."),
    ("Taj Mahal", "The Taj Mahal is one of the Seven Wonders of the World and is located in Agra, India."),
    ("Largest number of vegetarians",
     "India has the largest number of vegetarians in the world due to cultural and religious beliefs."),
    ("Cricket crazy nation",
     "India is a cricket-crazy nation, with the sport being the most popular in the country."),
    ("Rivers", "India is home to some of the world's largest and holiest rivers, including the Ganges, Yamuna, and Brahmaputra."),
    ("National animal", "The national animal of India is the lion."),
    ("Kumbh Mela", "The Kumbh Mela, a Hindu pilgrimage festival, is the largest gathering of people in the world."),
    ("Rabindranath Tagore", "Rabindranath Tagore, a Bengali poet, playwright, and philosopher, was the first non-European to win the Nobel Prize in Literature."),
    ("Mountains", "India is home to the world's highest mountain range, the Himalayas."),
    ("Jawaharlal Nehru", "Jawaharlal Nehru, India's first Prime Minister, was also known as 'Chacha Nehru' to children."),
    ("Colorful festivals", "India is famous for its colorful and vibrant festivals, such as Holi, Diwali, and Dussehra."),
    ("Mahatma Gandhi", "Mahatma Gandhi, the father of the nation, led India to independence through nonviolent civil disobedience."),
    ("Sari", "The sari is the traditional dress for women in India and comes in a variety of colors and styles."),
    ("Spices", "India is known for its aromatic and flavorful spices, used in a variety of dishes from all over the world."),
    ("Python is named after Monty Python, not the snake.", "Naming"),
    ("Python was created in 1989 by Guido van Rossum.", "Creation"),
    ("Python is an interpreted language, not compiled.", "Interpretation"),
    ("Python was designed to be easy to read and write.", "Design"),
    ("Python is used by companies such as Google, NASA, and Facebook.", "Usage"),
    ("India is the birthplace of chess."),
    ("The world's largest statue, the Statue of Unity, is located in India."),
    ("The Great Himalayas in India contain the highest peaks in the world, including Mount Everest."),
    ("The national symbol of India is the Lion Capital of Ashoka."),
    ("India is the world's largest democracy."),
    ("The ancient Indian text, the Vedas, is one of the oldest religious texts in the world."),
    ("India is the world's largest producer of mangoes."),
    ("The game of Snakes and Ladders originated in India."),
    ("The Indian national flag was designed by Pingali Venkayya."),
    ("What is your name.", "My name is AskAce."),
    ("what is the capital of France.", "Paris"),
    ("what is the tallest building in the world.", "Burj Khalifa"),
    ("what is the largest ocean in the world.", "Pacific Ocean"),
    ("What is the capital of France.", "The capital of France is Paris."),
    ("What is the largest ocean in the world.",
     "The largest ocean in the world is the Pacific Ocean."),
    ("What is the highest mountain in the world.", "Mount Everest"),
    ("What is the name of the first human to walk on the moon.", "Neil Armstrong"),
    ("What is the most populous country in the world.", "China"),
    ("What is the name of the first dinosaur ever discovered.", "Iguanodon"),
    ("What is the longest river in the world.", "Nile"),
    ("What is the capital of Brazil.", "Brasília"),
    ("What is the name of the world's largest desert.", "Sahara"),
    ("What is the capital of Germany.", "Berlin"),
    ("What is the name of the famous painting by Leonardo da Vinci that features Mona Lisa.", "The Mona Lisa"),
    ("What is the name of the famous Shakespeare play that features Romeo and Juliet.",
     "Romeo and Juliet"),
    ("What is the capital of Russia.", "Moscow"),
    ("What is the name of the famous Greek mythological hero who slayed the Minotaur.", "Theseus"),
    ("What is the capital of Italy.", "Rome"),
    ("What is the name of the world's largest waterfall.", "Angel Falls"),
    ("What is the capital of Japan.", "Tokyo"),
    ("What is the name of the famous Shakespeare play that features Hamlet.", "Hamlet"),
    ("What is the capital of Australia.", "Canberra"),
    ("What is the name of the famous Shakespeare play that features Macbeth.", "Macbeth"),
    ("What is the capital of South Africa.", "Pretoria"),
    ("What is the name of the famous Shakespeare play that features King Lear.", "King Lear"),
    ("What is the capital of Mexico.", "Mexico City"),
    ("What is the name of the famous Shakespeare play that features Othello.", "Othello"),
    ("What is the capital of Canada.", "Ottawa"),
    ("What is the name of the famous Shakespeare play that features The Tempest.", "The Tempest"),
    ("What is the capital of Argentina.", "Buenos Aires"),
    ("What is the capital of India.", "New Delhi"),
    ("What is the currency of India.", "Indian Rupee"),
    ("What is the largest state in India by area.", "Rajasthan"),
    ("What is the most populous state in India.", "Uttar Pradesh"),
    ("What is the official language of India.", "Hindi"),
    ("What is the name of India's National Anthem.", "Jana Gana Mana"),
    ("What is the name of India's flag.", "Tricolour"),
    ("What is the name of India's first Prime Minister.", "Jawaharlal Nehru"),
    ("What is the name of the famous temple in South India dedicated to Lord Rama.",
     "Sri Ranganathaswamy Temple"),
    ("What is the name of the famous shrine in North India dedicated to Lord Shiva.", "Amarnath Temple"),
    ("What is the name of the famous shrine in South India dedicated to Lord Venkateswara.",
     "Tirumala Venkateswara Temple"),
    ("What is the name of the famous shrine in North India dedicated to Lord Krishna.",
     "Banke Bihari Temple"),
    ("What is the name of the famous shrine in South India dedicated to Lord Ayyappa.",
     "Sabarimala Temple"),
    ("What is the name of the famous shrine in North India dedicated to Lord Hanuman.",
     "Hanuman Garhi Temple"),
    ("What is the name of the famous shrine in South India dedicated to Lord Murugan.",
     "Palani Murugan Temple"),
    ("What is the name of the famous shrine in North India dedicated to Lord Vishnu.",
     "Badrinath Temple"),
    ("What is the name of the famous shrine in South India dedicated to Lord Shiva.",
     "Meenakshi Temple"),
    ("What is the name of the famous shrine in North India dedicated to Lord Rama.",
     "Ram Janmabhoomi Temple"),
    ("What is the name of the famous shrine in South India dedicated to Lord Krishna.",
     "Udupi Krishna Temple"),
    ("What is the name of the famous shrine in North India dedicated to Lord Hanuman.",
     "Sankat Mochan Temple"),
    ("What is the name of the famous shrine in South India dedicated to Lord Ayyappa.", "Ayyappa Temple"),
    ("What is the name of the famous shrine in North India dedicated to Lord Murugan.",
     "Katra Vaishno Devi Temple"),
    ("What is the name of the famous shrine in South India dedicated to Lord Venkateswara.",
     "Tirupati Balaji Temple"),
    ("What is the name of the famous shrine in North India dedicated to Lord Vishnu.",
     "Ramanathaswamy Temple"),
    ("What is the name of the famous shrine in South India dedicated to Lord Shiva.",
     "Mahabalipuram Shore Temple"),
    ("What is the name of the famous shrine in North India dedicated to Lord Rama.",
     "Ayodhya Ram Temple"),
    ("What is the name of the famous shrine in South India dedicated to Lord Krishna.",
     "Guruvayur Temple"),
    ("What is the name of the famous shrine in North India dedicated to Lord Hanuman.",
     "Baijnath Dham Temple"),
    ("What is the name of the famous shrine in South India dedicated to Lord Ayyappa.", "Sabari Temple"),
    ("Who discovered the Zero.", "Aryabhata"),
    ("What is the most important discovery made by India in the field of science and technology.",
     "The discovery of zero"),
    ("What was India's contribution to the field of Astronomy.",
     "In the field of Astronomy, India was the first to develop a system of mathematics based on the decimal system."),
    ("What was the contribution of India to the field of Medicine.",
     "The ancient Indian Medical Text, Charaka Samhita, which provides comprehensive knowledge on health and diseases, was a pioneering work in the field of Medicine."),
    ("What was the contribution of India to the field of Surgery.",
     "In ancient India, the Sushruta Samhita was written, which is considered one of the first treatises on surgical techniques."),
    ("What was the contribution of India to the field of Metallurgy.",
     "India was one of the first places where Iron was smelted and used for tools and weapons."),
    ("What was India's contribution to the field of Mathematics.",
     "India was one of the first places to develop the decimal system and algorithms for arithmetic operations."),
    ("What was the contribution of India to the field of Navigation.",
     "In ancient India, navigators used the stars, the monsoon winds, and mathematical calculations to navigate across the Indian Ocean and beyond."),
    ("What was the contribution of India to the field of Architecture.",
     "India has a rich history of Architecture, with famous structures like the Taj Mahal and the rock-cut temples of Ellora and Ajanta."),
    ("What was the contribution of India to the field of Philosophy.",
     "India has a rich history of philosophical thought, with ancient schools like Vedanta, Samkhya, and Yoga."),
    ("What was the contribution of India to the field of Spirituality.",
     "India is the birthplace of several spiritual traditions like Hinduism, Buddhism, and Jainism, which have had a profound impact on the world."),
    ("Did you know that India is the only country to have a border shaped like a diamond.",
     "Yes, it is a fact"),
    ("Did you know that the national animal of India is the Bengal Tiger.",
     "Yes, it is a fact"),
    ("Did you know that the first rocket in India was transported on a cycle.",
     "Yes, it is a fact"),
    ("Did you know that the game of Snakes & Ladders was created in ancient India.",
     "Yes, it is a fact"),
    ("Did you know that India has the largest postal network in the world with over 154,000 post offices.", "Yes, it is a fact"),
    ("Did you know that the world's first university was established in India over 2,500 years ago.", "Yes, it is a fact"),
    ("Did you know that Yoga originated in ancient India and has been practiced for over 5,000 years.", "Yes, it is a fact"),
    ("Did you know that the Sistine Chapel of India, the Ajanta Caves, have paintings that are over 1,500 years old.", "Yes, it is a fact"),
    ("Did you know that India has the second largest road network in the world, spanning over 4.7 million km.", "Yes, it is a fact"),
    ("Did you know that India is the largest producer of mangoes in the world.",
     "Yes, it is a fact"),
    ("Did you know that the Indian Constitution is the longest written constitution of any sovereign country in the world.", "Yes, it is a fact"),
    ("Did you know that India has over 1.2 billion people, making it the second most populous country in the world.", "Yes, it is a fact"),
    ("Did you know that India has more vegetarians than the rest of the world combined.",
     "Yes, it is a fact"),
    ("Did you know that India has over 1 million kilometers of coastline, making it the 6th longest coastline in the world.", "Yes, it is a fact"),
    ("Did you know that the Taj Mahal in India is one of the Seven Wonders of the World and attracts millions of tourists each year.", "Yes, it is a fact"),
    ("Did you know that India has the largest film industry in the world, producing over 1,000 films annually in multiple languages.", "Yes, it is a fact"),
    ("Did you know that India is the birthplace of four major religions: Hinduism, Buddhism, Jainism, and Sikhism.", "Yes, it is a fact"),
    ("Did you know that India has the largest population of domesticated elephants in the world.", "Yes, it is a fact"),
    ("Did you know that the game of chess was invented in ancient India and was known as Chaturanga.", "Yes, it is a fact"),
    ("Did you know that India has the highest cricket ground in the world, located in the town of Chail, Himachal Pradesh.", "Yes, it is a fact"),
    ("Did you know that India is the largest democracy in the world, with over 900 million eligible voters in the 2019 general election.", "Yes, it is a fact"),
    ("Did you know that the India-Pakistan partition in 1947 is the largest mass migration in human history, with over 15 million people displaced.", "Yes, it is a fact"),
]

def generate_fun_fact():
    """
    Generates a random fun fact from the list 'fun_facts' and returns it with a 
    colored 'Fun Fact' prefix.
    """
    fact, category = random.choice(fun_facts)
    return colored(f"\nFun Fact ({fact}): {category}", "magenta")
